front/urls.py
from django.urls import path
from . import  views

app_name = 'front'

urlpatterns = [
    path('', views.index, name='index'),
    path(r'login/', views.login, name='login'),
    path('work/', views.work, name='work'),
    path('refreshlog/<int:page>', views.refresh_log, name='refresh_log'),
    path('logout/', views.logout, name='logout'),
    path('connect/admin/', views.connect_admin, name='connect_admin'),
]

refreshHuaweiCdn/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('front.urls')),
]

front/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(unique=True, max_length=32, null=False)
    pwd = models.CharField(max_length=320, null=False)
    addtime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Domain(models.Model):
    name = models.CharField(unique=True, max_length=32, null=False)
    cate = models.ForeignKey("Cloud", on_delete=False)

    def __str__(self):
        return self.name


class Cloud(models.Model):
    name = models.CharField(unique=True, max_length=32, null=False)
    domain_rule = models.CharField(unique=True, max_length=64)

    def __str__(self):
        return self.name


class FreshStatus(models.Model):
    name = models.CharField(max_length=16)

    def __str__(self):
        return self.name


class FreshLog(models.Model):
    user = models.ForeignKey("User", on_delete=False)
    name = models.ForeignKey("Domain", on_delete=False)
    cate = models.ForeignKey("Cloud", on_delete=False)
    url = models.CharField(max_length=120)
    freshtime = models.DateTimeField(auto_now=True)
    state = models.ForeignKey("FreshStatus", on_delete=False)
    task_id = models.CharField(max_length=32)
    # def __str__(self):
    #     return self.id


class UserLoginLog(models.Model):
    name = models.ForeignKey("User", on_delete=False)
    logintime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

front/forms.py
from django import forms
from .models import User


class LoginForm(forms.Form):
    name = forms.CharField(max_length=32, label="账号", widget=forms.TextInput(attrs={"class": "form-control"}))
    pwd = forms.CharField(max_length=32, label="密码", widget=forms.PasswordInput(attrs={"class": "form-control"}))

    def clean(self):
        num = User.objects.filter(name=self.cleaned_data.get('name')).count()
        print(num)
        if num == 0:
            raise forms.ValidationError("账号不存在！")
        else:
            if self.cleaned_data.get("pwd") != User.objects.filter(name=self.cleaned_data.get('name')).first().pwd:
                raise forms.ValidationError("密码错误！")
        return self.cleaned_data


class RefreshForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))
    fresh_type = forms.ChoiceField(choices=((1, '文件'), (2, '目录')), widget=forms.RadioSelect(attrs={"class": "text-center"}))

front/views.py
from django.shortcuts import render, redirect, reverse
from .forms import LoginForm, RefreshForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import UserLoginLog, User, Domain, Cloud, FreshLog, FreshStatus
from front.controller.myfun import get_clound_type
from django.core.paginator import Paginator
from django.http import HttpResponse
from subprocess import PIPE,Popen
from functools import wraps


def user_login_req(f):
	@wraps(f)
	def decorate_function(request, *args, **kwargs):
		if not request.session.__contains__('user_name') or request.session.get("user_name") is None:
			return redirect(reverse("front:login"))
		return f(request, *args, **kwargs)

	return decorate_function


@user_login_req
def index(request):
	return redirect(reverse("front:login"))
	#return render(request, 'front/index.html')


def login(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
	else:
		form = LoginForm()
	print(form.is_valid())
	if form.is_valid():
		print(form.cleaned_data)
		user = User.objects.filter(name=form.cleaned_data.get('name')).first()
		loginlog = UserLoginLog(name=user)
		loginlog.save()
		request.session.set_expiry(0)
		request.session["user_name"] = form.cleaned_data.get('name')
		return redirect(reverse("front:work"))
	return render(request, 'front/login.html', {"form": form})


@user_login_req
def work(request):
	if request.method == 'POST':
		form = RefreshForm(request.POST)
	else:
		form = RefreshForm()
	print(form.is_valid())
	if form.is_valid():
		content = form.cleaned_data.get("content")
		print(form.cleaned_data)
		fresh_type = form.cleaned_data.get("fresh_type")
		if int(fresh_type) == 1:
			file_type = "file"
		elif int(fresh_type) == 2:
			file_type = "directory"
		url_list = content.strip().split()
		domain_list = list(set([v.split('/')[2] for v in url_list]))
		print(domain_list)
		for url in url_list:
			if int(fresh_type) == 2 and not url.endswith('/'):
				messages.add_message(request, messages.ERROR, "内容错误，目录刷新必须以'/'结尾，{}".format(url))
				continue
			elif int(fresh_type) == 1 and url.endswith('/'):
				messages.add_message(request, messages.ERROR, "内容错误，文件刷新不能以'/'结尾，{}".format(url))
				continue
			status_key = None
			task_id = 0
			v = url.split('/')[2]
			cloud_type = get_clound_type(v)
			print(cloud_type)
			if cloud_type == "未知云":
				status_key = "内容错误"
				messages.add_message(request, messages.ERROR, "内容错误，未识别的域名,请注意检查url，{}".format(url))
			cloud = Cloud.objects.filter(name=cloud_type).first()
			domain = Domain.objects.filter(name=v).first()
			if not domain:
				new_domain = Domain(name=v, cate=cloud)
				new_domain.save()
			else:
				domain.cate = cloud
				domain.save()
			domain = Domain.objects.filter(name=v).first()
			# 域名+平台判断完毕，平台名称不是“未知云”则开始调用刷新接口
			if cloud_type != "未知云":
				try:
					# 开始执行刷新接口
					p = Popen("/usr/bin/python2.7 /data/apache/www/huaweicloud/refreshHuaweiCdn/front/controller/pythonsdk_projects/refresh_cdn.py {} {}".format(file_type, url), stdout=PIPE, stderr=PIPE, shell=True) 
					out = p.stdout.read().decode("utf-8").strip()
					# 获得task_id
					print("-------")
					print(out)
					print("-------")
					if out != "error":
						task_id = out
						messages.add_message(request, messages.SUCCESS, "{},提交成功，稍后可在操作记录中查看状态！".format(url))
						status_key = "已提交"
					else:
						status_key = "提交失败"
						messages.add_message(request, messages.ERROR, "提交失败，{}，请尝试重新提交！".format(url))
				except Exception as e:
					status_key = "提交失败"
					messages.add_message(request, messages.ERROR, "提交失败，{}，请尝试重新提交！".format(url))

			user_name = request.session.get("user_name")
			user = User.objects.filter(name=user_name).first()
			if status_key is not None:
				status = FreshStatus.objects.filter(name=status_key).first()
			fresh_log = FreshLog(name=domain, cate=cloud, url=url, user=user, state=status, task_id=task_id)
			fresh_log.save()
	return render(request, 'front/work.html', {"form": form})


@user_login_req
def refresh_log(request, page=1):
	user_name = request.session.get("user_name")
	user = User.objects.filter(name=user_name).first()
	log = FreshLog.objects.filter(user=user).order_by('-freshtime').all()
	paginator = Paginator(log, 10)
	if page > paginator.num_pages:
		page = paginator.num_pages
	elif page <= 0:
		page = 1
	elif page is None:
		page = 1
	loaded = paginator.page(page)
	print(paginator.num_pages)
	return render(request, "front/refreshlog.html", {"log": loaded})


@user_login_req
def connect_admin(request):
	return render(request, "front/connect_admin.html")



def logout(request):
#	del request.session["user_name"]
	request.session.pop("user_name", None)
	return redirect(reverse("front:login"))

front/templates/front/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="icon" href="http://www.miaoju.cn/favicon.ico">
    <title>xxxx自助刷新cdn工具</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
     {% block css %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}


<script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{#<script src="{% static 'js/ajax.js' %}"></script>#}
{% block js %}
{% endblock %}
</body>
</html>

front/templates/front/connect_admin.html
{% extends "front/base.html" %}
{% block content %}
    <div class="row">
        <nav class="navbar navbar-form navbar-header navbar-inverse navbar-fixed-top">
            <div class="container">
                <a href="#" class="navbar-brand">华为云-自助刷新cdn工具</a>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'front:work' %}" id="fresh-log" class="cdn">继续提交</a></li>
                    <li><a href="{% url 'front:refresh_log' page=1 %}" id="fresh-log" class="cdn">操作记录</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'front:logout' %}">退出系统</a></li>
{#                    <li><a href="#">联系管理员</a></li>#}
                </ul>
            </div>
        </nav>
        <div class="clearfix"></div>
        <div style="margin-top: 60px;">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">

            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/my.js' %}"></script>
{% endblock %}

front/templates/front/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>清理cdn</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
     {% block css %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}

<h1>hello</h1>

<script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{#<script src="{% static 'js/ajax.js' %}"></script>#}
{% block js %}
{% endblock %}
</body>
</html>

front/templates/front/login.html
{% extends "front/base.html" %}
{% block content %}
    <div class="row">
        <div class="container">
            <div class="col-md-4 col-md-push-4" style="margin-top: 200px;">
                <h3 class="text-center">xxxCDN工具</h3>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_table }}
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary btn-block" value="登陆">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/front/page.html
{% macro page(data,url) -%}
{% if data %}
<ul class="pagination pagination-sm no-margin pull-right">
    <li><a href="{{ url_for(url,page=1) }}">首页</a></li>

    {% if data.has_prev %}
    <li><a href="{{ url_for(url,page=data.prev_num) }}">上一页</a></li>
    {% else %}
    <li class="disabled"><a href="#">上一页</a></li>
    {% endif %}

    {% for v in data.iter_pages() %}
        {% if v == data.page %}
        <li class="active"><a href="#">{{ v }}</a></li>
        {% else %}
        <li ><a href="{{ url_for(url,page=v) }}">{{ v }}</a></li>
        {% endif %}
    {% endfor %}

    {% if data.has_next %}
    <li><a href="{{ url_for(url,page=data.next_num) }}">下一页</a></li>
    {% else %}
    <li class="disabled"><a href="#">下一页</a></li>
    {% endif %}

    <li><a href="{{ url_for(url,page=data.pages) }}">尾页</a></li>
</ul>
{% endif %}
{%- endmacro %}

front/templates/front/refreshlog.html
{% extends "front/base.html" %}
{% block content %}
    <div class="row">
        <nav class="navbar navbar-form navbar-header navbar-inverse navbar-fixed-top">
            <div class="container">
                <a href="#" class="navbar-brand">华为云-自助刷新cdn工具</a>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'front:work' %}" id="fresh-log" class="cdn">继续提交</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'front:logout' %}">退出系统</a></li>
<!--                    <li><a href="{% url 'front:connect_admin' %}">联系管理员</a></li> -->
                </ul>
            </div>
        </nav>
        <div class="clearfix"></div>
        <div style="margin-top: 60px;">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
                <table class="table table-hover  table-bordered text-center">
                    <thead>
                    <tr>
                        <td>id</td>
                        <td>云平台</td>
                        <td>url</td>
                        <td>提交时间</td>
                        <td>状态</td>
                    </tr>
                    {% for v in log %}
                        <tr>
                            <td>{{ v.id }}</td>
                            <td>{{ v.cate }}</td>
                            <td>{{ v.url }}</td>
                            <td>{{ v.freshtime }}</td>
                            <td>{{ v.state }}</td>
                        </tr>
                    {% endfor %}
                    </thead>
                </table>
                <div class="box-footer clearfix">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        <li><a href="{%  url 'front:refresh_log' page=1 %}">首页</a></li>
                        {% if log.has_previous %}
                            <li><a href="{%  url 'front:refresh_log' page=log.previous_page_number %}">上一页</a></li>
                        {% else %}
                            <li class="disabled" style="color: #ff0000"><a href="#">上一页</a></li>
                        {% endif %}
                        <li class="disabled" style="color: #ff0000"><a href="{%  url 'front:refresh_log' page=log.number %}" >{{ log.number }} of {{ log.paginator.num_pages }}</a></li>
                        {% if log.has_next %}
                            <li><a href="{%  url 'front:refresh_log' page=log.next_page_number %}">下一页</a></li>
                        {% else %}
                            <li class="disabled" style="color: #ff0000"><a href="#">下一页</a></li>
                        {% endif %}
                        <li><a href="{%  url 'front:refresh_log' page=log.paginator.num_pages %}">尾页</a></li>
                    </ul>
                    <p>第{{ log.number }}页，共{{ log.paginator.num_pages }}页</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/my.js' %}"></script>
{% endblock %}

front/templates/front/work.html
{% extends "front/base.html" %}
{% block content %}
    <div class="row">
        <nav class="navbar navbar-form navbar-header navbar-inverse navbar-fixed-top">
            <div class="container">
                <a href="#" class="navbar-brand">华为云-自助刷新cdn工具</a>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'front:refresh_log' page=1 %}" id="fresh-log" class="cdn">操作记录</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'front:logout' %}">退出系统</a></li>
<!--                    <li><a href="{% url 'front:connect_admin' %}">联系管理员</a></li> -->
                </ul>
            </div>
        </nav>
        <div class="clearfix"></div>
        <div style="margin-top: 60px;">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
                <form action="" method="post">
                    <h4 class="text-center">请输入需要的文件或目录的URL，<strong>一行一个，回车换行，</strong>目录请以'/'结尾，生效时间在5-10分钟</h4>
                    {% for msg in messages %}
                        {% if msg.tags == "error" %}
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <h4><i class="icon fa fa-check"></i> 提交失败</h4>
                                {{ msg }}
                            </div>
                        {% endif %}
                        {% if msg.tags == "success" %}
                            <div class="alert alert-success alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <h4><i class="icon fa fa-check"></i> 提交成功</h4>
                                {{ msg }}
                            </div>
                        {% endif %}
                    {% endfor %}
                    {% csrf_token %}
                    {{ form.content }}
                    <div class="form-group text-center">
                        {{ form.fresh_type }}
                    </div>
                    <div class="text-center">
                        <input type="submit" value="提交并刷新" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/my.js' %}"></script>
{% endblock %}